language: python

python:
  - "3.7.3"

install:
  - pip install -r requirements.txt

script:
  - pyinstaller main.py -F -w -n DuelEditor.out

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: dist/DuelEditor.out
  skip_cleanup: true
  on:
    tags: true