language: python
os: windows

python:
    - "3.7.3"

install:
- pip install -r requirements.txt

script:
  - pyinstaller main.py -F -w -n DuelEditor.exe

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: dist/DuelEditor.exe
  skip_cleanup: true
  on:
    tags: true