# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Operator_list = QtWidgets.QListWidget(self.centralwidget)
        self.Operator_list.setGeometry(QtCore.QRect(1130, 20, 141, 341))
        self.Operator_list.setObjectName("Operator_list")
        item = QtWidgets.QListWidgetItem()
        self.Operator_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Operator_list.addItem(item)
        self.label_ope = QtWidgets.QLabel(self.centralwidget)
        self.label_ope.setGeometry(QtCore.QRect(1190, 0, 41, 16))
        self.label_ope.setObjectName("label_ope")
        self.Operator_detail = QtWidgets.QTextBrowser(self.centralwidget)
        self.Operator_detail.setGeometry(QtCore.QRect(1130, 380, 141, 151))
        self.Operator_detail.setObjectName("Operator_detail")
        self.label_target = QtWidgets.QLabel(self.centralwidget)
        self.label_target.setGeometry(QtCore.QRect(870, 0, 81, 20))
        self.label_target.setObjectName("label_target")
        self.Target_list = QtWidgets.QListWidget(self.centralwidget)
        self.Target_list.setGeometry(QtCore.QRect(830, 20, 141, 341))
        self.Target_list.setObjectName("Target_list")
        self.Delete_target = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_target.setGeometry(QtCore.QRect(830, 370, 141, 28))
        self.Delete_target.setObjectName("Delete_target")
        self.Target_detail = QtWidgets.QTextBrowser(self.centralwidget)
        self.Target_detail.setGeometry(QtCore.QRect(830, 420, 141, 141))
        self.Target_detail.setObjectName("Target_detail")
        self.CreateCard_Button = QtWidgets.QPushButton(self.centralwidget)
        self.CreateCard_Button.setGeometry(QtCore.QRect(980, 190, 131, 28))
        self.CreateCard_Button.setObjectName("CreateCard_Button")
        self.MoveCard_Button = QtWidgets.QPushButton(self.centralwidget)
        self.MoveCard_Button.setGeometry(QtCore.QRect(980, 300, 131, 28))
        self.MoveCard_Button.setObjectName("MoveCard_Button")
        self.CommentCard_Button = QtWidgets.QPushButton(self.centralwidget)
        self.CommentCard_Button.setGeometry(QtCore.QRect(980, 380, 131, 28))
        self.CommentCard_Button.setObjectName("CommentCard_Button")
        self.Comment_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Comment_Button.setGeometry(QtCore.QRect(980, 410, 131, 28))
        self.Comment_Button.setObjectName("Comment_Button")
        self.DuelFrame = QtWidgets.QWidget(self.centralwidget)
        self.DuelFrame.setGeometry(QtCore.QRect(10, 0, 811, 631))
        self.DuelFrame.setObjectName("DuelFrame")
        self.Self_Ex = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_Ex.setGeometry(QtCore.QRect(10, 500, 141, 121))
        self.Self_Ex.setObjectName("Self_Ex")
        self.label_self_hands = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands.setGeometry(QtCore.QRect(50, 470, 81, 20))
        self.label_self_hands.setObjectName("label_self_hands")
        self.Self_Hand = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_Hand.setGeometry(QtCore.QRect(220, 500, 141, 121))
        self.Self_Hand.setObjectName("Self_Hand")
        self.label_self_hands_2 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_2.setGeometry(QtCore.QRect(260, 470, 81, 20))
        self.label_self_hands_2.setObjectName("label_self_hands_2")
        self.label_self_hands_3 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_3.setGeometry(QtCore.QRect(710, 390, 81, 20))
        self.label_self_hands_3.setObjectName("label_self_hands_3")
        self.Self_S1 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_S1.setGeometry(QtCore.QRect(130, 410, 111, 51))
        self.Self_S1.setObjectName("Self_S1")
        self.Self_S2 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_S2.setGeometry(QtCore.QRect(240, 410, 111, 51))
        self.Self_S2.setObjectName("Self_S2")
        self.Self_S3 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_S3.setGeometry(QtCore.QRect(350, 410, 111, 51))
        self.Self_S3.setObjectName("Self_S3")
        self.Self_S4 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_S4.setGeometry(QtCore.QRect(460, 410, 111, 51))
        self.Self_S4.setObjectName("Self_S4")
        self.Self_S5 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_S5.setGeometry(QtCore.QRect(570, 410, 111, 51))
        self.Self_S5.setObjectName("Self_S5")
        self.Self_P2 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_P2.setGeometry(QtCore.QRect(690, 420, 111, 41))
        self.Self_P2.setObjectName("Self_P2")
        self.label_self_hands_9 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_9.setGeometry(QtCore.QRect(30, 390, 81, 20))
        self.label_self_hands_9.setObjectName("label_self_hands_9")
        self.Self_P1 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_P1.setGeometry(QtCore.QRect(10, 420, 111, 41))
        self.Self_P1.setObjectName("Self_P1")
        self.label_self_hands_10 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_10.setGeometry(QtCore.QRect(30, 310, 81, 20))
        self.label_self_hands_10.setObjectName("label_self_hands_10")
        self.Self_Field = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_Field.setGeometry(QtCore.QRect(10, 340, 111, 41))
        self.Self_Field.setObjectName("Self_Field")
        self.label_self_hands_11 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_11.setGeometry(QtCore.QRect(710, 330, 81, 20))
        self.label_self_hands_11.setObjectName("label_self_hands_11")
        self.Self_LP = QtWidgets.QLineEdit(self.DuelFrame)
        self.Self_LP.setGeometry(QtCore.QRect(690, 360, 111, 21))
        self.Self_LP.setObjectName("Self_LP")
        self.Self_M5 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_M5.setGeometry(QtCore.QRect(570, 360, 111, 51))
        self.Self_M5.setObjectName("Self_M5")
        self.Self_M1 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_M1.setGeometry(QtCore.QRect(130, 360, 111, 51))
        self.Self_M1.setObjectName("Self_M1")
        self.Self_M2 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_M2.setGeometry(QtCore.QRect(240, 360, 111, 51))
        self.Self_M2.setObjectName("Self_M2")
        self.Self_M4 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_M4.setGeometry(QtCore.QRect(460, 360, 111, 51))
        self.Self_M4.setObjectName("Self_M4")
        self.Self_M3 = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_M3.setGeometry(QtCore.QRect(350, 360, 111, 51))
        self.Self_M3.setObjectName("Self_M3")
        self.label_self_hands_14 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_14.setGeometry(QtCore.QRect(480, 470, 81, 20))
        self.label_self_hands_14.setObjectName("label_self_hands_14")
        self.Self_Grave = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_Grave.setGeometry(QtCore.QRect(440, 500, 141, 121))
        self.Self_Grave.setObjectName("Self_Grave")
        self.Self_Banish = QtWidgets.QListWidget(self.DuelFrame)
        self.Self_Banish.setGeometry(QtCore.QRect(650, 500, 141, 121))
        self.Self_Banish.setObjectName("Self_Banish")
        self.label_self_hands_15 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_15.setGeometry(QtCore.QRect(690, 470, 81, 20))
        self.label_self_hands_15.setObjectName("label_self_hands_15")
        self.label_self_hands_16 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_16.setGeometry(QtCore.QRect(30, 160, 81, 20))
        self.label_self_hands_16.setObjectName("label_self_hands_16")
        self.label_self_hands_18 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_18.setGeometry(QtCore.QRect(710, 240, 81, 20))
        self.label_self_hands_18.setObjectName("label_self_hands_18")
        self.Enemy_P1 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_P1.setGeometry(QtCore.QRect(690, 190, 111, 41))
        self.Enemy_P1.setObjectName("Enemy_P1")
        self.Enemy_M4 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_M4.setGeometry(QtCore.QRect(240, 240, 111, 51))
        self.Enemy_M4.setObjectName("Enemy_M4")
        self.label_self_hands_19 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_19.setGeometry(QtCore.QRect(710, 160, 81, 20))
        self.label_self_hands_19.setObjectName("label_self_hands_19")
        self.Enemy_S3 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_S3.setGeometry(QtCore.QRect(350, 190, 111, 51))
        self.Enemy_S3.setObjectName("Enemy_S3")
        self.ExM_2 = QtWidgets.QListWidget(self.DuelFrame)
        self.ExM_2.setGeometry(QtCore.QRect(460, 300, 111, 51))
        self.ExM_2.setObjectName("ExM_2")
        self.Enemy_LP = QtWidgets.QLineEdit(self.DuelFrame)
        self.Enemy_LP.setGeometry(QtCore.QRect(10, 270, 111, 21))
        self.Enemy_LP.setObjectName("Enemy_LP")
        self.Enemy_Field = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_Field.setGeometry(QtCore.QRect(690, 270, 111, 41))
        self.Enemy_Field.setObjectName("Enemy_Field")
        self.Enemy_P2 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_P2.setGeometry(QtCore.QRect(10, 190, 111, 41))
        self.Enemy_P2.setObjectName("Enemy_P2")
        self.Enemy_S2 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_S2.setGeometry(QtCore.QRect(460, 190, 111, 51))
        self.Enemy_S2.setObjectName("Enemy_S2")
        self.ExM_1 = QtWidgets.QListWidget(self.DuelFrame)
        self.ExM_1.setGeometry(QtCore.QRect(240, 300, 111, 51))
        self.ExM_1.setObjectName("ExM_1")
        self.Enemy_M2 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_M2.setGeometry(QtCore.QRect(460, 240, 111, 51))
        self.Enemy_M2.setObjectName("Enemy_M2")
        self.Enemy_M1 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_M1.setGeometry(QtCore.QRect(570, 240, 111, 51))
        self.Enemy_M1.setObjectName("Enemy_M1")
        self.label_self_hands_21 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_21.setGeometry(QtCore.QRect(30, 240, 81, 20))
        self.label_self_hands_21.setObjectName("label_self_hands_21")
        self.Enemy_S4 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_S4.setGeometry(QtCore.QRect(240, 190, 111, 51))
        self.Enemy_S4.setObjectName("Enemy_S4")
        self.Enemy_S1 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_S1.setGeometry(QtCore.QRect(570, 190, 111, 51))
        self.Enemy_S1.setObjectName("Enemy_S1")
        self.Enemy_S5 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_S5.setGeometry(QtCore.QRect(130, 190, 111, 51))
        self.Enemy_S5.setObjectName("Enemy_S5")
        self.Enemy_M5 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_M5.setGeometry(QtCore.QRect(130, 240, 111, 51))
        self.Enemy_M5.setObjectName("Enemy_M5")
        self.Enemy_M3 = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_M3.setGeometry(QtCore.QRect(350, 240, 111, 51))
        self.Enemy_M3.setObjectName("Enemy_M3")
        self.Enemy_Banish = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_Banish.setGeometry(QtCore.QRect(650, 40, 141, 121))
        self.Enemy_Banish.setObjectName("Enemy_Banish")
        self.Enemy_Ex = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_Ex.setGeometry(QtCore.QRect(10, 40, 141, 121))
        self.Enemy_Ex.setObjectName("Enemy_Ex")
        self.label_self_hands_17 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_17.setGeometry(QtCore.QRect(480, 10, 81, 20))
        self.label_self_hands_17.setObjectName("label_self_hands_17")
        self.label_self_hands_4 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_4.setGeometry(QtCore.QRect(260, 10, 81, 20))
        self.label_self_hands_4.setObjectName("label_self_hands_4")
        self.Enemy_Hand = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_Hand.setGeometry(QtCore.QRect(220, 40, 141, 121))
        self.Enemy_Hand.setObjectName("Enemy_Hand")
        self.Enemy_Grave = QtWidgets.QListWidget(self.DuelFrame)
        self.Enemy_Grave.setGeometry(QtCore.QRect(440, 40, 141, 121))
        self.Enemy_Grave.setObjectName("Enemy_Grave")
        self.label_self_hands_12 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_12.setGeometry(QtCore.QRect(50, 10, 81, 20))
        self.label_self_hands_12.setObjectName("label_self_hands_12")
        self.label_self_hands_20 = QtWidgets.QLabel(self.DuelFrame)
        self.label_self_hands_20.setGeometry(QtCore.QRect(690, 10, 81, 20))
        self.label_self_hands_20.setObjectName("label_self_hands_20")
        self.Delete_target_2 = QtWidgets.QPushButton(self.DuelFrame)
        self.Delete_target_2.setGeometry(QtCore.QRect(140, 310, 91, 28))
        self.Delete_target_2.setObjectName("Delete_target_2")
        self.Delete_target_3 = QtWidgets.QPushButton(self.DuelFrame)
        self.Delete_target_3.setGeometry(QtCore.QRect(580, 310, 91, 28))
        self.Delete_target_3.setObjectName("Delete_target_3")
        self.EraseCard_Button = QtWidgets.QPushButton(self.centralwidget)
        self.EraseCard_Button.setGeometry(QtCore.QRect(980, 220, 131, 28))
        self.EraseCard_Button.setObjectName("EraseCard_Button")
        self.Dest_Box = QtWidgets.QComboBox(self.centralwidget)
        self.Dest_Box.setGeometry(QtCore.QRect(980, 270, 131, 22))
        self.Dest_Box.setObjectName("Dest_Box")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.Dest_Box.addItem("")
        self.label_target_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_target_2.setGeometry(QtCore.QRect(1010, 0, 81, 20))
        self.label_target_2.setObjectName("label_target_2")
        self.NewCard_line = QtWidgets.QLineEdit(self.centralwidget)
        self.NewCard_line.setGeometry(QtCore.QRect(980, 20, 131, 21))
        self.NewCard_line.setObjectName("NewCard_line")
        self.Newcard_List = QtWidgets.QListWidget(self.centralwidget)
        self.Newcard_List.setGeometry(QtCore.QRect(980, 50, 131, 131))
        self.Newcard_List.setObjectName("Newcard_List")
        self.DeleteOpe_Button = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteOpe_Button.setGeometry(QtCore.QRect(1130, 540, 141, 28))
        self.DeleteOpe_Button.setObjectName("DeleteOpe_Button")
        self.CopyOpe_Button = QtWidgets.QPushButton(self.centralwidget)
        self.CopyOpe_Button.setGeometry(QtCore.QRect(1130, 570, 141, 28))
        self.CopyOpe_Button.setObjectName("CopyOpe_Button")
        self.MoveOpe_Button = QtWidgets.QPushButton(self.centralwidget)
        self.MoveOpe_Button.setGeometry(QtCore.QRect(1130, 600, 141, 28))
        self.MoveOpe_Button.setObjectName("MoveOpe_Button")
        self.LPTarget_Box = QtWidgets.QComboBox(self.centralwidget)
        self.LPTarget_Box.setGeometry(QtCore.QRect(990, 450, 131, 22))
        self.LPTarget_Box.setObjectName("LPTarget_Box")
        self.LPTarget_Box.addItem("")
        self.LPTarget_Box.addItem("")
        self.LP_line = QtWidgets.QLineEdit(self.centralwidget)
        self.LP_line.setGeometry(QtCore.QRect(990, 480, 131, 21))
        self.LP_line.setObjectName("LP_line")
        self.AddLP_Button = QtWidgets.QPushButton(self.centralwidget)
        self.AddLP_Button.setGeometry(QtCore.QRect(990, 510, 131, 28))
        self.AddLP_Button.setObjectName("AddLP_Button")
        self.DecLP_Button = QtWidgets.QPushButton(self.centralwidget)
        self.DecLP_Button.setGeometry(QtCore.QRect(990, 540, 131, 28))
        self.DecLP_Button.setObjectName("DecLP_Button")
        self.CgeLP_Button = QtWidgets.QPushButton(self.centralwidget)
        self.CgeLP_Button.setGeometry(QtCore.QRect(990, 570, 131, 28))
        self.CgeLP_Button.setObjectName("CgeLP_Button")
        self.HalLP_Button = QtWidgets.QPushButton(self.centralwidget)
        self.HalLP_Button.setGeometry(QtCore.QRect(990, 600, 131, 28))
        self.HalLP_Button.setObjectName("HalLP_Button")
        self.NewCard_Rename = QtWidgets.QLineEdit(self.centralwidget)
        self.NewCard_Rename.setGeometry(QtCore.QRect(830, 570, 141, 21))
        self.NewCard_Rename.setObjectName("NewCard_Rename")
        self.NewCard_Rename_Button = QtWidgets.QPushButton(self.centralwidget)
        self.NewCard_Rename_Button.setGeometry(QtCore.QRect(830, 600, 141, 28))
        self.NewCard_Rename_Button.setObjectName("NewCard_Rename_Button")
        self.Comment_Line = QtWidgets.QLineEdit(self.centralwidget)
        self.Comment_Line.setGeometry(QtCore.QRect(980, 350, 131, 21))
        self.Comment_Line.setObjectName("Comment_Line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DuelEditor"))
        __sortingEnabled = self.Operator_list.isSortingEnabled()
        self.Operator_list.setSortingEnabled(False)
        item = self.Operator_list.item(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Operator_list.item(1)
        item.setText(_translate("MainWindow", "2"))
        self.Operator_list.setSortingEnabled(__sortingEnabled)
        self.label_ope.setText(_translate("MainWindow", "操作"))
        self.Operator_detail.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">操作详细</p></body></html>"))
        self.label_target.setText(_translate("MainWindow", "操作对象"))
        self.Delete_target.setText(_translate("MainWindow", "列表中删除"))
        self.Target_detail.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">对象卡片</p></body></html>"))
        self.CreateCard_Button.setText(_translate("MainWindow", "←创建卡片"))
        self.MoveCard_Button.setText(_translate("MainWindow", "移动卡片"))
        self.CommentCard_Button.setText(_translate("MainWindow", "卡片注释"))
        self.Comment_Button.setText(_translate("MainWindow", "操作注释"))
        self.label_self_hands.setText(_translate("MainWindow", "己方额外"))
        self.label_self_hands_2.setText(_translate("MainWindow", "己方手卡"))
        self.label_self_hands_3.setText(_translate("MainWindow", "己方右灵摆"))
        self.label_self_hands_9.setText(_translate("MainWindow", "己方左灵摆"))
        self.label_self_hands_10.setText(_translate("MainWindow", "己方场地"))
        self.label_self_hands_11.setText(_translate("MainWindow", "己方基本分"))
        self.label_self_hands_14.setText(_translate("MainWindow", "己方墓地"))
        self.label_self_hands_15.setText(_translate("MainWindow", "己方除外"))
        self.label_self_hands_16.setText(_translate("MainWindow", "对方右灵摆"))
        self.label_self_hands_18.setText(_translate("MainWindow", "对方场地"))
        self.label_self_hands_19.setText(_translate("MainWindow", "对方左灵摆"))
        self.label_self_hands_21.setText(_translate("MainWindow", "对方基本分"))
        self.label_self_hands_17.setText(_translate("MainWindow", "对方墓地"))
        self.label_self_hands_4.setText(_translate("MainWindow", "对方手卡"))
        self.label_self_hands_12.setText(_translate("MainWindow", "对方额外"))
        self.label_self_hands_20.setText(_translate("MainWindow", "对方除外"))
        self.Delete_target_2.setText(_translate("MainWindow", "打开"))
        self.Delete_target_3.setText(_translate("MainWindow", "保存"))
        self.EraseCard_Button.setText(_translate("MainWindow", "删除卡片"))
        self.Dest_Box.setItemText(0, _translate("MainWindow", "己方手卡"))
        self.Dest_Box.setItemText(1, _translate("MainWindow", "己方魔陷_1"))
        self.Dest_Box.setItemText(2, _translate("MainWindow", "己方魔陷_2"))
        self.Dest_Box.setItemText(3, _translate("MainWindow", "己方魔陷_3"))
        self.Dest_Box.setItemText(4, _translate("MainWindow", "己方魔陷_4"))
        self.Dest_Box.setItemText(5, _translate("MainWindow", "己方魔陷_5"))
        self.Dest_Box.setItemText(6, _translate("MainWindow", "己方场地"))
        self.Dest_Box.setItemText(7, _translate("MainWindow", "己方灵摆_1"))
        self.Dest_Box.setItemText(8, _translate("MainWindow", "己方灵摆_2"))
        self.Dest_Box.setItemText(9, _translate("MainWindow", "己方怪兽_1"))
        self.Dest_Box.setItemText(10, _translate("MainWindow", "己方怪兽_2"))
        self.Dest_Box.setItemText(11, _translate("MainWindow", "己方怪兽_3"))
        self.Dest_Box.setItemText(12, _translate("MainWindow", "己方怪兽_4"))
        self.Dest_Box.setItemText(13, _translate("MainWindow", "己方怪兽_5"))
        self.label_target_2.setText(_translate("MainWindow", "新建列表"))
        self.DeleteOpe_Button.setText(_translate("MainWindow", "删除操作"))
        self.CopyOpe_Button.setText(_translate("MainWindow", "复制操作"))
        self.MoveOpe_Button.setText(_translate("MainWindow", "移动操作"))
        self.LPTarget_Box.setItemText(0, _translate("MainWindow", "己方"))
        self.LPTarget_Box.setItemText(1, _translate("MainWindow", "对方"))
        self.AddLP_Button.setText(_translate("MainWindow", "增加基本分"))
        self.DecLP_Button.setText(_translate("MainWindow", "减少基本分"))
        self.CgeLP_Button.setText(_translate("MainWindow", "变成基本分"))
        self.HalLP_Button.setText(_translate("MainWindow", "基本分减半"))
        self.NewCard_Rename_Button.setText(_translate("MainWindow", "重命名"))


